name: Code Review Workflow

on:
  pull_request:
    types: [unlabeled, labeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Needs review
        if: >
          contains(github.event.pull_request.labels.*.name, 'needs review') &&
          !contains(github.event.pull_request.labels.*.name, 'needs work') &&
          !contains(github.event.pull_request.labels.*.name, 'do not merge') &&
          !contains(github.event.pull_request.labels.*.name, 'ready for merge')
        uses: alex-page/github-project-automation-plus@v0.1.1
        with:
          project: Mbed TLS test PRs
          column: Needs review
          repo-token: ${{ secrets.AUTOMATION_TEST_TOKEN }}
      - name: Needs work
        if: >
          (!contains(github.event.pull_request.labels.*.name, 'needs review') ||
          contains(github.event.pull_request.labels.*.name, 'needs work') ||
          contains(github.event.pull_request.labels.*.name, 'do not merge')) &&
          !contains(github.event.pull_request.labels.*.name, 'ready for merge')
        uses: alex-page/github-project-automation-plus@v0.1.1
        with:
          project: Mbed TLS test PRs
          column: Needs work
          repo-token: ${{ secrets.AUTOMATION_TEST_TOKEN }}
